apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fpc1hi0uf-go
  janus-idp.io/tekton: fpc1hi0uf-go
  backstage.io/kubernetes-id: fpc1hi0uf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fpc1hi0uf-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
