apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fpc1hi0uf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fpc1hi0uf-go 
  name: fpc1hi0uf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fpc1hi0uf-go 
